version: "3.7"
services:
  frontend: # React.js frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    stdin_open: true

  backend: # Rust graqhl server
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - "./backend:/server"
    ports:
      - 3001:3001

  db: # postgresql database
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
