version: "3.7"
services:
  frontend: # React.js frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    env_file:
      - ./.env.dev
    ports:
      - 3000:3000
    stdin_open: true

  api: # rust graphql server
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
    env_file:
      - ./.env.dev
    environment:
      RUST_LOG: info
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - 3535:3535
    depends_on:
      - db
      - cache
    restart: always

  db: # postgresql database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migrations/up:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env.dev
    restart: always

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
